name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Se o nome da sua branch principal for 'master', troque aqui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Instalar dependências e rodar testes
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest

      # Login no Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem
      - name: Build Docker image
        run: docker build -t rafaelkrm/reports-service:latest .

      # Push para o Docker Hub
      - name: Push Docker image
        run: docker push rafaelkrm/reports-service:latest
